---
- name: "Build docker images and push them to GCR"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Get timestamp for docker tag"
      shell: "(date +%Y%m%d%H%M%S)"
      register: tag

    - name: Print tag
      debug:
        var: tag.stdout

    - name: Build preprocessing container image
      community.general.docker_image:
        build:
          path: "/preprocessing"
          platform: "linux/amd64/v2"
        name: "gcr.io/{{ gcp_project }}/ccb-preprocessing:{{ tag.stdout }}"
        source: build

    - name: Push preprocessing image to GCR
      community.general.docker_image:
        name: gcr.io/{{ gcp_project }}/ccb-preprocessing:{{ tag.stdout}}
        repository: gcr.io/{{ gcp_project }}/ccb-preprocessing:{{ tag.stdout}}
        push: yes
        source: local

    - name: Build download_from_dac container image
      community.general.docker_image:
        build:
          path: "/download_from_dac"
          platform: "linux/amd64/v2"
        name: "gcr.io/{{ gcp_project }}/ccb-download_from_dac:{{ tag.stdout }}"
        source: build

    - name: Push download_from_dac image to GCR
      community.general.docker_image:
        name: gcr.io/{{ gcp_project }}/ccb-download_from_dac:{{ tag.stdout}}
        repository: gcr.io/{{ gcp_project }}/ccb-download_from_dac:{{ tag.stdout}}
        push: yes
        source: local

    - name: Build model1 container image
      community.general.docker_image:
        build:
          path: "/model1"
          platform: "linux/amd64/v2"
        name: "gcr.io/{{ gcp_project }}/ccb-model1:{{ tag.stdout }}"
        source: build

    - name: Push model1 image to GCR
      community.general.docker_image:
        name: gcr.io/{{ gcp_project }}/ccb-model1:{{ tag.stdout}}
        repository: gcr.io/{{ gcp_project }}/ccb-model1:{{ tag.stdout}}
        push: yes
        source: local

    - name: Build model2 container image
      community.general.docker_image:
        build:
          path: "/model2"
          platform: "linux/amd64/v2"
        name: "gcr.io/{{ gcp_project }}/ccb-model2:{{ tag.stdout }}"
        source: build

    - name: Push model2 image to GCR
      community.general.docker_image:
        name: gcr.io/{{ gcp_project }}/ccb-model2:{{ tag.stdout}}
        repository: gcr.io/{{ gcp_project }}/ccb-model2:{{ tag.stdout}}
        push: yes
        source: local

    - name: "Save docker tag"
      shell: echo {{ tag.stdout}} > .docker-tag
