FROM node:14.9.0-buster-slim

# Ensure we don't run the app as root.
RUN set -ex; \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends openssl && \
    useradd -ms /bin/bash app -d /home/app -G sudo -u 2000 -p "$(openssl passwd -1 Passw0rd)" && \
    mkdir -p /app && \
    chown app:app /app

EXPOSE 3000

WORKDIR /app

# Switch to the new user
USER app

# Copy package.json and yarn.lock, install dependencies
COPY --chown=app:app package.json yarn.lock ./
RUN yarn install

# Copy the rest of your app's source code
COPY --chown=app:app . .

# Expose port 3000 for the development server
EXPOSE 3000

# Start the development server
CMD ["yarn", "start"]